In [8]:
import numpy as np

np_a = np.array(['A', 'B', 'C'])
print(np_a)

['A' 'B' 'C']


In [9]:
np_a = np.array([[1,2],[3,4]])
print(np_a)

[[1 2]
 [3 4]]


In [11]:
a = np.array([1, 2, 3,4,5], ndmin = 2)
print(a)

[[1 2 3 4 5]]


In [14]:
a = np.array([1, 2, 3], dtype = float)
print(a)

[1. 2. 3.]


In [16]:
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)], dtype = dt)
print (a)

[(10,) (20,) (30,)]


In [17]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')])
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student)
print (a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [21]:
a = np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print (a)

[[1 2]
 [3 4]
 [5 6]]


In [22]:
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print (b)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a = np.arange(24)
print a

In [25]:
a = np.arange(1,20, 2)
print (a)

[ 1  3  5  7  9 11 13 15 17 19]


In [28]:
x = np.array([1,2,3,4,5], dtype = np.int32)
print(x.itemsize)

4


In [31]:
x = np.empty([3,2], dtype = int)
print (x)

[[1 2]
 [3 4]
 [5 6]]


In [32]:
x = np.zeros(5)
print (x)

[0. 0. 0. 0. 0.]


In [34]:
x = np.ones(5, dtype = int)
print (x)

[1 1 1 1 1]


In [38]:
x = [1,2,3]
a = np.asarray(x)
print (a)

[1 2 3]


In [40]:
x = [(1,2,3),(4,5)]
a = np.asarray(x, dtype=object)
print (a)

[(1, 2, 3) (4, 5)]


In [42]:
x = np.linspace(10,20,5, endpoint = False)
print (x)

[10. 12. 14. 16. 18.]


In [44]:
a = np.arange(10)
print(a)
s = slice(2,7,2)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [45]:
a = np.arange(10)
b = a[2:7:2]
print(b)

[2 4 6]


In [47]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print (a)
print ('Now we will slice the array from the index a[1:]')
print (a[1][1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[4 5]
